'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/context/AuthContext';
import { auth, db } from '@/lib/firebase';
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';
import Tesseract from 'tesseract.js';
import styles from './page.module.css';
import { 
  ArrowLeft, 
  Upload, 
  ShieldCheck, 
  Search, 
  CheckCircle2, 
  AlertCircle,
  Eye,
  Lock,
  Zap,
  FileText
} from 'lucide-react';
import { Button, Card } from '@/components';

export default function EligibilityPage() {
  const router = useRouter();
  const { user } = useAuth();
  const [status, setStatus] = useState<'idle' | 'reading' | 'success' | 'fail' | 'error'>('idle');
  const [resultData, setResultData] = useState<{ age: number; isEligible: boolean } | null>(null);
  const [errorMessage, setErrorMessage] = useState('');

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setStatus('reading');
    setResultData(null);
    setErrorMessage('');

    try {
      let imageSource: string | HTMLCanvasElement = '';

      // Handle PDF
      if (file.type === 'application/pdf') {
        const pdfjsLib = await import('pdfjs-dist');
        // @ts-ignore
        pdfjsLib.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjsLib.version}/build/pdf.worker.min.mjs`;
        
        const arrayBuffer = await file.arrayBuffer();
        const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
        const page = await pdf.getPage(1);
        const viewport = page.getViewport({ scale: 2 });
        const canvas = document.createElement('canvas');
        const context = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;

        if (context) {
          await page.render({ canvasContext: context, viewport }).promise;
          imageSource = canvas;
        }
      } else {
        imageSource = await new Promise((resolve) => {
          const reader = new FileReader();
          reader.onload = (e) => resolve(e.target?.result as string);
          reader.readAsDataURL(file);
        });
      }

      // 1. OCR Processing
      const { data: { text } } = await Tesseract.recognize(imageSource, 'eng');

      // 2. Extract DOB and Calculate Age
      const dateRegex = /(\d{2})[\/\-\.](\d{2})[\/\-\.](\d{4})/;
      const match = text.match(dateRegex);

      if (match) {
        const { age, isEligible } = await import('@/utils/age').then(m => m.calculateAge(match[0]));
        
        setResultData({ age, isEligible });
        setStatus(isEligible ? 'success' : 'fail');

        if (user) {
          await updateUserStatus(isEligible, age);
        }
      } else {
        setStatus('error');
        setErrorMessage("Could not detect a valid Date of Birth. Please ensure your ID card or PDF is clear and well-lit.");
      }
    } catch (err: any) {
      console.error("Processing Error:", err);
      setStatus('error');
      setErrorMessage("Something went wrong during processing. Please try again.");
    }
  };

  const downloadCriteria = async () => {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();
    
    doc.setFillColor(0, 97, 255);
    doc.rect(0, 0, 210, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.text('OFFICIAL VOTER ELIGIBILITY CRITERIA', 105, 13, { align: 'center' });

    doc.setTextColor(26, 32, 44);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('1. Age Requirement', 20, 40);
    doc.setFont('helvetica', 'normal');
    doc.text('A citizen must be at least 18 years old on the qualifying date of the year.', 20, 48);

    doc.setFont('helvetica', 'bold');
    doc.text('2. Citizenship', 20, 65);
    doc.setFont('helvetica', 'normal');
    doc.text('Must be a citizen of India.', 20, 73);

    doc.setFont('helvetica', 'bold');
    doc.text('3. Sound Mind', 20, 90);
    doc.setFont('helvetica', 'normal');
    doc.text('Must not be declared of unsound mind by a competent court.', 20, 98);

    doc.setFont('helvetica', 'bold');
    doc.text('4. No Criminal Disqualification', 20, 115);
    doc.setFont('helvetica', 'normal');
    doc.text('Must not be disqualified due to certain electoral offenses or corrupt practices.', 20, 123);

    doc.setFontSize(10);
    doc.setTextColor(160, 174, 192);
    doc.text('Document generated by Chunav-Sarathi Platform', 105, 280, { align: 'center' });

    doc.save('Voter_Eligibility_Criteria.pdf');
  };

  const updateUserStatus = async (isEligible: boolean, age: number) => {
    if (!user) return;
    try {
      await setDoc(doc(db, "users", user.uid), {
        isEligible,
        calculatedAge: age,
        verifiedAt: serverTimestamp(),
        verificationType: 'document_ocr'
      }, { merge: true });
    } catch (err) {
      console.error("Firebase Update Error:", err);
    }
  };

  return (
    <main className={styles.container}>
      <div className={styles.content}>
        <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem'}}>
          <button className={styles.backBtn} style={{marginBottom: 0}} onClick={() => router.back()}>
            <ArrowLeft size={20} /> Back
          </button>
          <Button variant="outline" size="sm" onClick={downloadCriteria}>
            <FileText size={16} style={{marginRight: '8px'}} /> Official Criteria
          </Button>
        </div>

        <header className={styles.header}>
          <h1 className="gradient-text">Eligibility Vault</h1>
          <p>
            Verify your voting eligibility instantly using our secure document OCR system. 
            Now supporting <strong>Images</strong> and <strong>PDF</strong> documents.
          </p>
        </header>

        <section className={styles.verificationCard}>
          <div className={styles.uploadZone}>
            <div className={styles.uploadIcon}>
              {status === 'reading' ? <div className={styles.loader}></div> : <Upload size={32} />}
            </div>
            <div className={styles.uploadText}>
              <h3>{status === 'reading' ? 'Analyzing Document...' : 'Upload ID Document'}</h3>
              <p>Supports Aadhaar, Voter ID (PNG, JPG, PDF)</p>
            </div>
            <input 
              type="file" 
              className={styles.fileInput} 
              accept="image/*,application/pdf" 
              onChange={handleFileUpload}
              disabled={status === 'reading'}
            />
          </div>

          {status !== 'idle' && status !== 'reading' && (
            <div className={styles.statusBox}>
              {status === 'success' && (
                <div className={styles.result}>
                  <div className={`${styles.resultBadge} ${styles.eligible}`}>
                    <CheckCircle2 size={18} /> Eligible to Vote
                  </div>
                  <div className={styles.resultText}>
                    <h2>Identity Verified</h2>
                    <p>
                      Calculated Age: <strong>{resultData?.age} years</strong>. 
                      {user ? ' Your status has been synced to your profile.' : ' You are ready to register as a voter.'}
                    </p>
                  </div>
                </div>
              )}

              {status === 'fail' && (
                <div className={styles.result}>
                  <div className={`${styles.resultBadge} ${styles.notEligible}`}>
                    <AlertCircle size={18} /> Underage
                  </div>
                  <div className={styles.resultText}>
                    <h2>Registration Restricted</h2>
                    <p>
                      Calculated Age: <strong>{resultData?.age} years</strong>. 
                      Citizens must be at least 18 years old to participate.
                    </p>
                  </div>
                </div>
              )}

              {status === 'error' && (
                <div className={styles.result}>
                  <div className={`${styles.resultBadge} ${styles.notEligible}`}>
                    <AlertCircle size={18} /> Analysis Failed
                  </div>
                  <div className={styles.resultText}>
                    <h2>Precision Error</h2>
                    <p>{errorMessage}</p>
                    <Button variant="outline" size="sm" style={{marginTop: '1rem'}} onClick={() => setStatus('idle')}>
                      Try Again
                    </Button>
                  </div>
                </div>
              )}
            </div>
          )}
        </section>

        <div className={styles.infoGrid}>
          <div className={styles.infoItem}>
            <div className={styles.smallIcon}><Eye size={20} /></div>
            <div>
              <h4>Hybrid Processing</h4>
              <p>We handle both high-res images and multi-page PDFs locally on your device.</p>
            </div>
          </div>
          <div className={styles.infoItem}>
            <div className={styles.smallIcon}><Lock size={20} /></div>
            <div>
              <h4>Secure Metadata</h4>
              <p>We only save the verified eligibility bit, ensuring your identity documents remain private.</p>
            </div>
          </div>
          <div className={styles.infoItem}>
            <div className={styles.smallIcon}><Zap size={20} /></div>
            <div>
              <h4>Official Standards</h4>
              <p>Built according to ECI age verification guidelines for the 2024 general elections.</p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}

